### ISSUE TITLE
Errors with MSTest 3.2.0 and later

### ISSUE THREAD

**Issue by menees** [meziantou/Meziantou.Polyfill#44]
### Version of the Meziantou.Polyfill NuGet package

1.0.41

### Description

When I use Meziantou.Polyfill with MSTest 3.2.0 through 3.6.3 (the latest version), I get the following errors on the net48 target:

``` text
1>------ Build started: Project: MSTestPolyfillClash, Configuration: Debug Any CPU ------
1>C:\Dev\Testing\MSTestPolyfillClash\obj\Debug\net48\Meziantou.Polyfill\Meziantou.Polyfill.PolyfillGenerator\M_System.Collections.Immutable.ImmutableArray`1.AsSpan(System.Int32,System.Int32).g.cs(11,23,11,29): error CS1501: No overload for method 'AsSpan' takes 0 arguments
1>C:\Dev\Testing\MSTestPolyfillClash\obj\Debug\net48\Meziantou.Polyfill\Meziantou.Polyfill.PolyfillGenerator\M_System.Collections.Immutable.ImmutableArray`1.AsSpan(System.Range).g.cs(12,23,12,29): error CS1501: No overload for method 'AsSpan' takes 0 arguments
1>MSTestPolyfillClash -> C:\Dev\Testing\MSTestPolyfillClash\bin\Debug\net6.0\MSTestPolyfillClash.dll
1>Done building project "MSTestPolyfillClash.csproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```
[MSTestPolyfillClash.zip](https://github.com/user-attachments/files/17784412/MSTestPolyfillClash.zip)

Note: When I use Meziantou.Polyfill with MSTest 3.1.1, it compiles correctly. I just discovered this bug when I tried to upgrade my [Chords test project](https://github.com/menees/Chords/tree/master/tests) from MSTest 3.1.1 to 3.6.3.

### Reproduction Steps

The minimal code to reproduce this is the following .csproj class library project:

``` xml
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net6.0;net48</TargetFrameworks>
		<LangVersion>11</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<!-- This project builds with MSTest v3.1.1 but not with newer versions. -->
		<PackageReference Include="MSTest" Version="3.6.3" />
		<PackageReference Include="Meziantou.Polyfill" Version="1.0.41">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>
```

**Comment by meziantou** [comment]
There is a dependency on a very old version of [system.collections.immutable](https://www.nuget.org/packages/System.Collections.Immutable/). As a workaround, you can upgrade this package or you can disable the specific polyfills:

````
<PropertyGroup>
  <!-- Tip: The name of the generated polyfills are available in the generated "Debug.g.cs" file -->
  <MeziantouPolyfill_ExcludedPolyfills>M:System.Collections.Immutable.ImmutableArray.</MeziantouPolyfill_ExcludedPolyfills>
</PropertyGroup>
````

**Comment by meziantou** [comment]
Latest version includes the missing polyfill

**Comment by menees** [comment]
Thanks!
